name: Jekyll Deploy

on:
  push:
    branches:
    - master
  # redeploy once a day to update unpublished pages
  schedule:
  - cron: "0 2 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy to GitHub Pages
      uses: EdricChan03/action-build-deploy-ghpages@v2.2.1
      with:
        GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
